name: Deploy Weather-App
on:
    push:
        branches:
            - master
            - test-build
jobs:
    build:
        env:
          CI: false
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages
              run: npm install
            - name: Perform linting
              run: npm run lint:fix